### ISSUE TITLE
Running the server on a different port

### ISSUE THREAD

**Issue by jmontene** [joxeankoret/multiav#14]
Hello, I've been having problems running the multiav server. There doesn't seem to be documentation on how to do it. I tried using runserver.py, but it always fails with an error about the path from where is being run (even if I run it from the path it asks to be run from). Also, I can't find any place where the port number of the server could be changed

**Comment by joxeankoret** [comment]
Hi!

After the change to make it a Python packages, things changed and the documentation was not updated. I will do it soon. In order to run the _example_ Web API you can run the following command:

```
$ cd multiav
$ python scripts/runserver.py
```

This is a web.py application so, in case you want to specify in which port you want it to listen, just add the port at the end of the command line:

```
$ cd multiav
$ python scripts/runserver.py 8081
```
